on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: "testing github actions"
        run: pwd
      - name: "testing printing"
        run: echo mahmoud


jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
	/* will not download files on machine */
      - name: "before printing the folder containts"
        run: ls
	/* to download files using library or action اكشن جاهز */
      - uses: actions/checkout@v3

      - name: "after printing the folder containts"
        run: ls
$ why the .github folder not exists?
  as in linux any folder start with . is disappeard
	ls -a